
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(1, 0, 'pr_0000000001', 'The Mirror Crack-d from Side to Side - Cengage Learning');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(2, 0, 'pr_0000000002', 'The Stars- Tennis Balls - HarperPrism');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(3, 0, 'pr_0000000003', 'Jacob Have I Loved - Faber and Faber');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(4, 0, 'pr_0000000004', 'The Heart Is a Lonely Hunter - Kensington Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(5, 0, 'pr_0000000005', 'Waiting for the Barbarians - Boydell & Brewer');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(6, 0, 'pr_0000000006', 'No Highway - BBC Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(7, 0, 'pr_0000000007', 'The Stars- Tennis Balls - Manchester University Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(8, 0, 'pr_0000000008', 'The Lathe of Heaven - Harvill Press at Random House');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(9, 0, 'pr_0000000009', 'A Swiftly Tilting Planet - Imperial War Museum');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(10, 0, 'pr_0000000010', 'The Man Within - O-Reilly Media');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(11, 0, 'pr_0000000011', 'The Moving Toyshop - Adis International');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(12, 0, 'pr_0000000012', 'Consider the Lilies - Focal Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(13, 0, 'pr_0000000013', 'Of Mice and Men - Parachute Publishing');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(14, 0, 'pr_0000000014', 'O Jerusalem! - J. M. Dent');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(15, 0, 'pr_0000000015', 'Françoise Sagan - Harcourt Assessment');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(16, 0, 'pr_0000000016', 'Wildfire at Midnight - Marshall Cavendish');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(17, 0, 'pr_0000000017', 'A Swiftly Tilting Planet - Taylor & Francis');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(18, 0, 'pr_0000000018', 'A Darkling Plain - John Blake Publishing');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(19, 0, 'pr_0000000019', 'It-s a Battlefield - Darakwon Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(20, 0, 'pr_0000000020', 'The Skull Beneath the Skin - No Starch Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(21, 0, 'pr_0000000021', 'The Violent Bear It Away - Ellora-s Cave');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(22, 0, 'pr_0000000022', 'Let Us Now Praise Famous Men - United States Government Publishing Office');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(23, 0, 'pr_0000000023', 'No Longer at Ease - Vintage Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(24, 0, 'pr_0000000024', 'For Whom the Bell Tolls - Hogarth Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(25, 0, 'pr_0000000025', 'The Way Through the Woods - McClelland and Stewart');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(26, 0, 'pr_0000000026', 'Vanity Fair - Ace Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(27, 0, 'pr_0000000027', 'Lilies of the Field - Chatto and Windus');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(28, 0, 'pr_0000000028', 'For a Breath I Tarry - Tate Publishing & Enterprises');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(29, 0, 'pr_0000000029', 'Behold the Man - Atheneum Publishers');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(30, 0, 'pr_0000000030', 'I Will Fear No Evil - Atheneum Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(31, 0, 'pr_0000000031', 'An Instant In The Wind - Book League of America');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(32, 0, 'pr_0000000032', 'I Sing the Body Electric - Carcanet Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(33, 0, 'pr_0000000033', 'Eyeless in Gaza - University of Alaska Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(34, 0, 'pr_0000000034', 'In Death Ground - Gaspereau Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(35, 0, 'pr_0000000035', 'Nectar in a Sieve - Harry N. Abrams, Inc.');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(36, 0, 'pr_0000000036', 'Behold the Man - Book League of America');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(37, 0, 'pr_0000000037', 'If Not Now, When? - George Routledge & Sons');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(38, 0, 'pr_0000000038', 'Nine Coaches Waiting - Atheneum Publishers');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(39, 0, 'pr_0000000039', 'Sleep the Brave - Marshall Pickering');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(40, 0, 'pr_0000000040', 'To Sail Beyond the Sunset - Jaico Publishing House');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(41, 0, 'pr_0000000041', 'An Evil Cradling - Secker & Warburg');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(42, 0, 'pr_0000000042', 'Ring of Bright Water - McGraw-Hill Education');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(43, 0, 'pr_0000000043', 'The Line of Beauty - University of Minnesota Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(44, 0, 'pr_0000000044', 'A Farewell to Arms - Anvil Press Poetry');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(45, 0, 'pr_0000000045', 'Mr Standfast - Belknap Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(46, 0, 'pr_0000000046', 'The Lathe of Heaven - Eerdmans Publishing');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(47, 0, 'pr_0000000047', 'The Road Less Traveled - Scholastic Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(48, 0, 'pr_0000000048', 'Fame Is the Spur - HarperCollins');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(49, 0, 'pr_0000000049', 'The Wives of Bath - O-Reilly Media');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(50, 0, 'pr_0000000050', 'An Evil Cradling - D. Reidel');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(51, 0, 'pr_0000000051', 'Little Hands Clapping - Manor House Publishing');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(52, 0, 'pr_0000000052', 'The Stars- Tennis Balls - University of Alaska Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(53, 0, 'pr_0000000053', 'Nectar in a Sieve - Manning Publications');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(54, 0, 'pr_0000000054', 'That Hideous Strength - Pathfinder Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(55, 0, 'pr_0000000055', 'Tiger! Tiger! - Andrews McMeel Publishing');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(56, 0, 'pr_0000000056', 'The Cricket on the Hearth - Karadi Tales');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(57, 0, 'pr_0000000057', 'The Heart Is a Lonely Hunter - Unfinished Monument Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(58, 0, 'pr_0000000058', 'The Widening Gyre - Blackie and Son Limited');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(59, 0, 'pr_0000000059', 'That Hideous Strength - Emerald Group Publishing');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(60, 0, 'pr_0000000060', 'Beyond the Mexique Bay - Banner of Truth Trust');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(61, 0, 'pr_0000000061', 'What-s Become of Waring - Apress');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(62, 0, 'pr_0000000062', 'The Moving Toyshop - Dedalus Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(63, 0, 'pr_0000000063', 'His Dark Materials - Shoemaker & Hoard Publishers');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(64, 0, 'pr_0000000064', 'A Darkling Plain - Basic Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(65, 0, 'pr_0000000065', 'Recalled to Life - Dalkey Archive Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(66, 0, 'pr_0000000066', 'Little Hands Clapping - McClelland and Stewart');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(67, 0, 'pr_0000000067', 'Waiting for the Barbarians - Harry N. Abrams, Inc.');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(68, 0, 'pr_0000000068', 'The Violent Bear It Away - University of Akron Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(69, 0, 'pr_0000000069', 'Beneath the Bleeding - Liberty Fund');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(70, 0, 'pr_0000000070', 'Mother Night - Leafwood Publishers');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(71, 0, 'pr_0000000071', 'O Jerusalem! - United States Government Publishing Office');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(72, 0, 'pr_0000000072', 'A Glass of Blessings - Gaspereau Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(73, 0, 'pr_0000000073', 'The Last Temptation - Harcourt Assessment');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(74, 0, 'pr_0000000074', 'This Lime Tree Bower - André Deutsch');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(75, 0, 'pr_0000000075', 'Fear and Trembling - HarperTrophy');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(76, 0, 'pr_0000000076', 'Infinite Jest - Charles Scribner-s Sons');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(77, 0, 'pr_0000000077', 'To Say Nothing of the Dog - Harper & Row');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(78, 0, 'pr_0000000078', 'Butter In a Lordly Dish - Anvil Press Poetry');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(79, 0, 'pr_0000000079', 'Time of our Darkness - Athabasca University Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(80, 0, 'pr_0000000080', 'Taming a Sea Horse - Brill');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(81, 0, 'pr_0000000081', 'The Mirror Crack-d from Side to Side - Apress');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(82, 0, 'pr_0000000082', 'Butter In a Lordly Dish - Unfinished Monument Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(83, 0, 'pr_0000000083', 'Some Buried Caesar - Book League of America');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(84, 0, 'pr_0000000084', 'Things Fall Apart - Athabasca University Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(85, 0, 'pr_0000000085', 'Down to a Sunless Sea - Marshall Cavendish');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(86, 0, 'pr_0000000086', 'East of Eden - University of Minnesota Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(87, 0, 'pr_0000000087', 'The Yellow Meads of Asphodel - Darakwon Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(88, 0, 'pr_0000000088', 'The Golden Apples of the Sun - Virago Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(89, 0, 'pr_0000000089', 'Dance Dance Dance - Fairview Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(90, 0, 'pr_0000000090', 'I Sing the Body Electric - Golden Cockerel Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(91, 0, 'pr_0000000091', 'The Sun Also Rises - Jaico Publishing House');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(92, 0, 'pr_0000000092', 'An Instant In The Wind - Tarpaulin Sky Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(93, 0, 'pr_0000000093', 'The Waste Land - Tartarus Press');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(94, 0, 'pr_0000000094', 'To Say Nothing of the Dog - Anova Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(95, 0, 'pr_0000000095', 'Great Work of Time - Apress');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(96, 0, 'pr_0000000096', 'The Widening Gyre - Harper & Row');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(97, 0, 'pr_0000000097', 'The Last Enemy - Eel Pie Publishing');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(98, 0, 'pr_0000000098', 'A Scanner Darkly - Orchard Books');
INSERT INTO public.product (id, "version", product_id, product_name) VALUES(99, 0, 'pr_0000000099', 'Absalom, Absalom! - NavPress');